version: "3.9"

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www

  nginx:
    image: nginx:1.23-alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d:ro

